### ISSUE TITLE
Difference in implementation Access vs Excel ( FileSystemObject.OpenTextFile )

### ISSUE THREAD

**Issue by grsmith28** [GustavBrock/VBA.Compress#1]
Left comment on ExpertsExchange too.

I tried implementing in Excel and there seems to be a difference in the way that the FileSystemObject.OpenTextFile function works.  The parameter "ForWriting" is not valid in Excel; and need to specify 8 (which allows for appending to file).

As I write this, I wonder if this may also be due to me using late binding...

**Comment by GustavBrock** [comment]
Yes, it was due to the use of late binding; if used, the enum **IOMode** is lost.
The code module has been updated to V1.1.1 to handle this.
The function **FolderFileNames** has also been updated to run with late binding.
