### ISSUE TITLE
Error 91 with UNC Paths

### ISSUE THREAD

**Issue by unomasmas** [GustavBrock/VBA.Compress#2]
https://github.com/GustavBrock/VBA.Compress/blob/771ceefe13d7c84bc5dc0c519f6c5ca753030d43/FileCompress.bas#L1072

This line raise error 91 (Object variable or With block variable not set) when parameter is given in UNC format; i.e.:  
Path = "\\server1\web"
`ZipPath = FileSystemObject.GetFolder(Path).ParentFolder` will raise Err 91

**Comment by GustavBrock** [comment]
> Path = "\server1\web"

Try with the normal UNC syntax:

`Path = "\\server1\web"`

**Comment by unomasmas** [comment]
My path is a typo, sorry. I tried with `Path = "\\server1\web"`

An added problem is that in the previous line, `FileSystemObject.GetBaseName(Path)` returns an empty string, so the name of the zip to generate will be ".zip", the value of the constant `ZipExtension`:

https://github.com/GustavBrock/VBA.Compress/blob/771ceefe13d7c84bc5dc0c519f6c5ca753030d43/FileCompress.bas#L1071

**Comment by unomasmas** [comment]
I have not found a solution to get the name with `FileSystemObject`, so it is possible that there is a better solution than how I solved it. In my proposed solution It is also necessary to change line 1157 in the `With ShellApplication` block because the number of items will no longer be 1 (since the containing folder is not included in the zip) but the number of files and subfolders it contains. On the other hand, only non-empty folders are going to be included, so we need to find out how many there are. We need an additional function: `getNumberOfEmptyFolders`. I also add it.

This is the replacement for lines 1071 and 1072
```
If (FileSystemObject.GetDrive(FileSystemObject.GetDriveName(Path)).DriveType = Network) And FileSystemObject.GetFolder(Path).IsRootFolder Then
    If VBA.Right$(Path, 1) = "\" Then Path = VBA.Left$(Path, Len(Path) - 1)
    ZipName = VBA.Left$(Path, InStrRev(Path, "\")-1) & ZipExtension
    ZipPath = VBA.Mid$(Path, InStrRev(Path, "\")+1)
Else
    ZipName = FileSystemObject.GetBaseName(Path) & ZipExtension
    ZipPath = FileSystemObject.GetFolder(Path).ParentFolder
End If
```

This is the replacement for line 1157
```
Do Until .Namespace(CVar(ZipTemp)).Items.Count = (.Namespace(CVar(Path)).Items.count - getNumberOfEmptyFolders(.Namespace(CVar(Path)).Items)) Or Counter = 10
```
This is the additional function
```
#If EarlyBinding Then
Private Function getNumberOfEmptyFolders(fi As FolderItems) As Integer
    Dim item As FolderItem
#Else
Private Function getNumberOfEmptyFolders(fi As Object) As Integer
    Dim item As Object
#End If
    Dim iTmp As Integer
    
    For Each item In fi
        If item.isFolder Then
            If item.GetFolder.items.count = 0 Then
                iTmp = iTmp + 1
            End If
        End If
    Next item
    getNumberOfEmptyFolders = iTmp
End Function
```

**Comment by GustavBrock** [comment]
Thank you! I also noted your question on SO: [FileSystemObject: Retrieving folder name from UNC path](https://stackoverflow.com/questions/71864215/filesystemobject-retrieving-folder-name-from-unc-path).
The simple reason for the issue is, that I never tested the code with UNC paths. However, that's certainly a valid option to include, and I will look into it, but I can't tell when - it's quite busy here for the moment.

**Comment by GustavBrock** [comment]
I checked with UNC paths for both source and destination, for both `Zip/UnZip` and `Cab/DeCab`, with files, folders, and with subfolders, but I cannot replicate your issue, sorry. 
Fileshare was a _Windows Server 2019_ share. 
Thus, I have to conclude, that the issue you experience is related to something else outside these functions.

**Comment by unomasmas** [comment]
Are you sure you did the tests with the parameters that I used? Initially I found the problem in _Windows 10_ but I just did tests in _Windows Server 2019_ and the result has been reproduced.

The problem only arises if the shared folder is the one you want to compress. If you try to compress a subfolder of the root folder there is no problem.

`//Server/Folder` will give problems
`//Server/Folder/Subfolder` will not give any problem.

**Comment by GustavBrock** [comment]
Ah, I see. No, I didn't, but I did now, and - as you have found - it fails, because there is no parent folder.

However, that operation - to compress a fileshare root - is beyond the scope of the functions, as these are intended to work as closely to the behaviour in Windows Explorer as possible, and in Windows Explorer you can't zip/cab a fileshare, only a folder of a fileshare. 
Thus, I've modified the functions to ignore the attempt to compress a fileshare.
